### PR TITLE
Fix ci conda

### PR DESCRIPTION
**Pull request by steven-murray**
The aim of this PR is to fix the install on the CI environment, and to make it a faster.

### CODE REVIEW

**Comment by steven-murray** [comment]
@adeliegorce this is failing because it can't find some hera_pspec data files -- is it possible that these files are missing in the pypi distribution?

**Comment by adeliegorce** [comment]
The data files used in the `hera_pspec` tests are not included in the PyPi distribution because the size of the package would exceed the allowed limit (88MB > 60MB) and the users installing from PyPi have no reason to use the tests. Maybe we should make the `pspec_likelihood` tests standalone and include all the required data files in the `pspec_likelihood` repo rather than fetching them from `hera_psec`?

**Comment by steven-murray** [comment]
@adeliegorce that makes a lot of sense. Another way to get around this would be to have a separate repo of "test data" that can be shared by different repos (including `hera_pspec` and `pspec_likelihood`). Then you'd just have to clone that repo (which could be cached) on the CI for each repo that requires it. What do you think?

**Comment by adeliegorce** [comment]
That's the ideal option, I agree! I'm not sure how to do this - happy to hear your suggestions or to reproduce whatever you'd do for `pspec_likelihood` in `hera_pspec` :)

**Comment by steven-murray** [comment]
Hmmm, thinking about it further, I don't know if this is the best idea -- there's all kinds of decisions to make about how to manage files that might be needed only for one of the repos' tests. I think just copying over the relevant files to `pspec_likelihood` makes sense -- that way we have them at need in our repo.

**Comment by adeliegorce** [comment]
The best idea in theory might not be in practice :) I'm happy to follow the copying strategy - I think it is only a couple files anyway.

**Comment by steven-murray** [comment]
We'll need to wait for https://github.com/HERA-Team/uvtools/pull/145 to be merged and a new release on uvtools...

**Review by adeliegorce — APPROVED** [review]

**Comment by steven-murray** [comment]
@adeliegorce do you think these test errors are a pspec issue?

**Pull request merged**
